### ISSUE TITLE
Printing with `seconds`

### ISSUE THREAD

**Issue by camoy** [racket/frtime#13]
I have the following program:

```rkt
#lang frtime

(require (lifted (only-in racket/base displayln) displayln))
(displayln seconds)
(sleep 10)
```

My expectation is that it prints the current seconds, every second, for ten seconds. Instead, running on the command line, it only prints out for the first five seconds and then stops (no matter how long the sleep is):

```
1619300741
1619300742
1619300743
1619300744
1619300745
```

**Comment by ghcooper** [comment]
`displayln` isn't a function, so I'm not sure what the semantics should be here.

Operationally, applying a `lifted` version of `displayln` to `seconds` constructs a behavior that listens to changes in `seconds` and calls `displayln` on each successive value. However, there is no reference pinning that result behavior, so the garbage collector eventually removes it, which stops the printing.

What happens if you `(define foo (displayln seconds))`?

**Comment by camoy** [comment]
Sorry, I forgot to close out this issue. Shortly after I posted this, and re-reading the FrTime paper, I realized the problem was that the edges in the data flow graph are weak. I think this would be a useful caveat for the documentation (to be careful when lifting effectful operations), but I agree it's not a bug.
